### ISSUE TITLE
if template locale value is empty string, t() returns whole object instead

### ISSUE THREAD

**Issue by ahanoff** [aug-riedinger/i18n-node-yaml#4]
For example I have the following yaml https://gist.github.com/ahanoff/41c23d5ffea329afa4a765ab08777df0

If I read it like
`engine.t(root, 'abc', {}, 'en')`, I'm getting `{ en: '' }` in response instead of empty string. 

Is it by design or not? I assume should be empty string instead

**Comment by ahanoff** [comment]
Thanks @augnustin

**Comment by augnustin** [comment]
Hi @ahanoff 

Thanks for reporting the bug. It was not by design and the error came from the fact that `''` is falsey in JS.

I fixed the code, added a test on it and updated the npm package to version `1.0.4`. Do not hesitate to fetch the newer version now: https://www.npmjs.com/package/i18n-node-yaml

Best
